// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAOOBQ9RYe0QGeJssny6ys5pUZEYCytfQ',
    appId: '1:568108543532:web:0ed0c99de07482ab55ab89',
    messagingSenderId: '568108543532',
    projectId: 'movecity-unit',
    authDomain: 'movecity-unit.firebaseapp.com',
    storageBucket: 'movecity-unit.firebasestorage.app',
    measurementId: 'G-S6EMDCS4DY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3lCnTJxdK4lvV2MGTdcmB8_NbE8kYGoo',
    appId: '1:568108543532:android:a30f3cc130f9347e55ab89',
    messagingSenderId: '568108543532',
    projectId: 'movecity-unit',
    storageBucket: 'movecity-unit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5GwHWSncHyXUC2NWda8IciixdFoaxFmQ',
    appId: '1:568108543532:ios:051e7044fc5768de55ab89',
    messagingSenderId: '568108543532',
    projectId: 'movecity-unit',
    storageBucket: 'movecity-unit.firebasestorage.app',
    iosBundleId: 'com.example.movecity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5GwHWSncHyXUC2NWda8IciixdFoaxFmQ',
    appId: '1:568108543532:ios:051e7044fc5768de55ab89',
    messagingSenderId: '568108543532',
    projectId: 'movecity-unit',
    storageBucket: 'movecity-unit.firebasestorage.app',
    iosBundleId: 'com.example.movecity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAOOBQ9RYe0QGeJssny6ys5pUZEYCytfQ',
    appId: '1:568108543532:web:8a6442516b02d6fe55ab89',
    messagingSenderId: '568108543532',
    projectId: 'movecity-unit',
    authDomain: 'movecity-unit.firebaseapp.com',
    storageBucket: 'movecity-unit.firebasestorage.app',
    measurementId: 'G-QF3BMZBFSF',
  );
}
